services:
  scanretrival:
    container_name: api
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - 8000:8000
    depends_on:
      - db
  db:
    image: mysql
    env_file: ./app/envs/db.env
    ports:
     - 3306:3306
    volumes:
      - "./Data/DB:/var/lib/mysql"
  
  minio:
    image: quay.io/minio/minio
    ports:
      - 9000:9000
      - 9001:9001
    env_file: ./app/envs/minio.env
    volumes:
      - "./Data/Minio/data:/data"
    
    command: ["server","/data","--console-address", ":9001"]
    restart: unless-stopped